dist: trusty
sudo: required
language: java

deploy:
  provider: script
  script: mvn clean compile package

services:
  - docker

before_install:
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS quay.io

install:

script:
  - mvn clean compile package
  - docker build -t emergencyresponsedemo/missionservice:$TRAVIS_COMMIT .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag emergencyresponsedemo/missionservice:$TRAVIS_COMMIT quay.io/emergencyresponsedemo/missionservice:$TAG
  - docker push quay.io/emergencyresponsedemo/missionservice:$TAG
